name: Power Platform CI/CD

on:
  push:
    branches:
      - develop

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install .NET Core SDK (for pac CLI)
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'

      - name: Install Power Platform CLI via .NET Tool
        run: |
          dotnet tool install --global Microsoft.PowerApps.CLI.Tool
          echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

      - name: Install Power Platform Tools
        uses: microsoft/powerplatform-actions@v1.5.2
        with:
          version: latest

      - name: Authenticate to Power Platform
        uses: microsoft/powerplatform-actions@v1.5.2
        with:
          clientId: ${{ secrets.AZURE_CLIENT_ID }}
          tenantId: ${{ secrets.AZURE_TENANT_ID }}
          clientSecret: ${{ secrets.AZURE_CLIENT_SECRET}}
          environmentName: ODL_User 1696579's Environment

      - name: Validate Solution
        run: |
          pac solution validate --path "./solution_export" --solutionName "ContosoSolution" --target "test"

      - name: Deploy to Test Environment
        run: |
          pac solution deploy --path "./solution_export" --solutionName "ContosoSolution" --target "test"
